---

- name: Getting Ldb source file
  get_url: url={{ ldb_tarball_url }} dest=/tmp/ldb-{{ ldb_version }}.tar.gz mode=0777
  register: ldb_source
  ignore_errors: false

- name: Extracting Ldb files
  unarchive:
    src: /tmp/ldb-{{ ldb_version }}.tar.gz
    dest: /tmp/
    remote_src: yes
  when: ldb_source.changed
  register: ldb_source_unpack

- name: Configuring Ldb source
  command: "./configure --prefix={{ ldb_prefix_path }}"
  args:
    chdir: "{{ ldb_install_dir }}"
  when: ldb_source_unpack.changed
  register: ldb_configure

- name: Build the Ldb default target
  make:
    chdir: "{{ ldb_install_dir }}"
    params:
      NUM_THREADS: 2
  when: ldb_configure.changed

- name: Installing ldb as root
  make:
    chdir: "{{ ldb_install_dir }}"
    target: install
  become: yes

