---

- name: Getting Tdb source file
  get_url: url={{ tdb_tarball_url }} dest=/tmp/tdb-{{ tdb_version }}.tar.gz mode=0777
  register: tdb_source
  ignore_errors: false

- name: Extracting Tdb files
  unarchive:
    src: /tmp/tdb-{{ tdb_version }}.tar.gz
    dest: /tmp/
    remote_src: yes
  when: tdb_source.changed
  register: tdb_source_unpack

- name: Configuring Tdb source
  command: "./configure --prefix={{ tdb_prefix_path }}"
  args:
    chdir: "{{ tdb_install_dir }}"
  when: tdb_source_unpack.changed
  register: tdb_configure

- name: Build the Tdb default target
  make:
    chdir: "{{ tdb_install_dir }}"
    params:
      NUM_THREADS: 2
  when: tdb_configure.changed

- name: Installing tdb as root
  make:
    chdir: "{{ tdb_install_dir }}"
    target: install
  become: yes

