---

- name: Getting {{ src_name }} source file
  get_url: url={{ src_tarball_url }} dest={{ src_install_file }} mode=0777 timeout=15
  register: src_source
  ignore_errors: false

- name: Extracting {{ src_name }} files
  unarchive:
    src: "{{ src_install_file }}"
    dest: /tmp/
    remote_src: yes
  when: src_source.changed
  register: src_source_unpack

- name: Configuring {{ src_name }} source
  command: "./configure --prefix={{ src_prefix_path }}"
  args:
    chdir: "{{ src_install_dir }}"
  when: src_source_unpack.changed
  register: src_configure

- name: Build the {{ src_name }} default target
  make:
    chdir: "{{ src_install_dir }}"
    params:
      NUM_THREADS: 2
  when: src_configure.changed

- name: Installing {{ src_name }} as root
  make:
    chdir: "{{ src_install_dir }}"
    target: install
  become: yes

