---

- name: Getting Talloc source file
  get_url: url={{ talloc_tarball_url }} dest=/tmp/talloc-{{ talloc_version }}.tar.gz mode=0777
  register: talloc_source
  ignore_errors: false

- name: Extracting Talloc files
  unarchive:
    src: /tmp/talloc-{{ talloc_version }}.tar.gz
    dest: /tmp/
    remote_src: yes
  when: talloc_source.changed
  register: talloc_source_unpack

- name: Configuring Talloc source
  command: "./configure --prefix={{ talloc_prefix_path }}"
  args:
    chdir: "{{ talloc_install_dir }}"
  when: talloc_source_unpack.changed
  register: talloc_configure

- name: Build the Talloc default target
  make:
    chdir: "{{ talloc_install_dir }}"
    params:
      NUM_THREADS: 2
  when: talloc_configure.changed

- name: Installing talloc as root
  make:
    chdir: "{{ talloc_install_dir }}"
    target: install
  become: yes

