---

- name: Getting Samba4 source file
  get_url: url={{ samba_tarball_url }} dest=/tmp/samba-{{ samba_version }}.tar.gz mode=0777
  register: samba_source
  ignore_errors: false

- name: Extracting Samba4 files
  unarchive:
    src: /tmp/samba-{{ samba_version }}.tar.gz
    dest: /tmp/
    remote_src: yes
  when: samba_source.changed
  register: samba_source_unpack

- name: Configuring Samba4 source
  command: "./configure --prefix={{ samba_prefix_path }}"
  args:
    chdir: "{{ samba_install_dir }}"
  when: samba_source_unpack.changed
  register: samba_configure

- name: Build the Samba4 default target
  make:
    chdir: "{{ samba_install_dir }}"
    params:
      NUM_THREADS: 2
  when: samba_configure.changed

- name: Installing samba as root
  make:
    chdir: "{{ samba_install_dir }}"
    target: install
  become: yes

