---

- name: Getting Tevent source file
  get_url: url={{ tevent_tarball_url }} dest=/tmp/tevent-{{ tevent_version }}.tar.gz mode=0777
  register: tevent_source
  ignore_errors: false

- name: Extracting Tevent files
  unarchive:
    src: /tmp/tevent-{{ tevent_version }}.tar.gz
    dest: /tmp/
    remote_src: yes
  when: tevent_source.changed
  register: tevent_source_unpack

- name: Configuring Tevent source
  command: "./configure --prefix={{ tevent_prefix_path }}"
  args:
    chdir: "{{ tevent_install_dir }}"
  when: tevent_source_unpack.changed
  register: tevent_configure

- name: Build the Tevent default target
  make:
    chdir: "{{ tevent_install_dir }}"
    params:
      NUM_THREADS: 2
  when: tevent_configure.changed

- name: Installing tevent as root
  make:
    chdir: "{{ tevent_install_dir }}"
    target: install
  become: yes

